const PREFIX = 'FILTERS_';

export const UPDATE_SEARCH = `${PREFIX}UPDATE_SEARCH`;
export const TOGGLE_TAG = `${PREFIX}TOGGLE_TAG`;
export const TOGGLE_CATEGORY = `${PREFIX}TOGGLE_CATEGORY`;
export const RESET_FILTERS = `${PREFIX}RESET_FILTERS`;
